### PR TITLE
eslint and editorconfig from mantra

### PR DESCRIPTION
**Pull request by sakulstra**

### CODE REVIEW

**Comment by sakulstra** [comment]
This was probably to early. We should first decide if we want to go with mantra/react. I'd suggest we do, as it brings the advantage of having a defined folder structure and testing, but it's open for any input.

**Comment by ecerroni** [comment]
I don't know mantra, neither react. But I believe in learning by doing, so I vouche for using them.

Let's this project go with mantra/react

**Comment by serkandurusoy** [comment]
Did you guys watch the latest transmission episodes, especially the parts about mantra vs guide? 

The takeaways are:
- mantra is good, no doubt! and is in many ways parallel with what mdg's cooking
- mantra is "client only" vs guide is full stack
- mantra is "platform agnostic"  vs guide is meteor oriented

I strongly believe we should go with what guide has to offer. MDG is preparing a guide overhaul for 1.3 and it will be even better.

Regarding the react vs angular vs blaze discussion, I think we can touch and cover the complete ground here. I am currently working on a rough draft about what I have in mind about this project and it will surprize you in this regard ;)

Finally, ES2015 it definitely is!

**Comment by sakulstra** [comment]
I've seen the transmission episodes and got some other takeaways:

Pro:
- Mantras specifications are more strict
- Mantra has at least some opinion about testing (the guide will get this too in the near future)
- Mantra tackles react version problems
- Mantra has an opinion about codestyle (the guide will get this too)
- Mantra has some naming conventions

Con:
- Mantra restricts itself to react
- Mantra is more complex
- The guide has more intense implementation examples

Anyways, if we stick to one of them we can probably switch pretty easily, so i would suggest we go with whatever the mentors are more familiar with. I think till 1.3 is finally out (and perhaps even after that) mantra will get (a lot) at least some changes and it could get kind of tricky to always refactor our stuff - so going with the guide seems okay for me, too.

**Comment by kaiyes** [comment]
I am not really willing to use Mantra. I rather wait a bit for MDG's official Response. I believe that will be much better in every sense. MDG is a bit slow I agree, but when they come up with something, they nail it.

**Comment by sakulstra** [comment]
I'm no eslint guru but I think this setup should even work with blaze or am I wrong? So we could simply rebase and merge this?
The discussion started by myself about mantra or not was kind of misleading - eslint is universal. For testing we can wait till 1.3 is out.
#9
PS:
But this eslint config will force us to use ES2015 and imports ...

**Comment by serkandurusoy** [comment]
I think we may actually move on to 1.3 and upgrade as new beta versions come in. And begin implementing eslint and imports

**Comment by sakulstra** [comment]
I'd love that. Ill do it in friday if noone else did it before :)
Am 07.03.2016 12:35 nachm. schrieb "Serkan Durusoy" <
notifications@github.com>:

**Comment by serkandurusoy** [comment]
Great!

**Pull request closed without merging**
